bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   get 'home/about' => 'homes#about'
   get 'user/:id/top' => 'users#top', as: 'top'
   get 'user/:id/about' => 'users#about', as: 'about'

   get '/search', to: 'searchs#search'

   get 'search/result' => 'searchs#result'

  resources :users, only: [:create, :index, :show, :destroy, :edit, :update, :delete]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update, :delete] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create]
   end

  resources :book_comments, only: [:destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

end

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Bookers", root_path %>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
         <% if user_signed_in? %>
        <li><i class="fas fa-home">
         <%= link_to 'Home', user_path(current_user.id) %></i>
         <i class="fas fa-users">
         <%= link_to 'Users', users_path %></i>
         <i class="fas fa-book-open">
         <%= link_to 'Books', books_path %></i>
         <i class="fas fa-sign-out-alt">
         <%= link_to "logout", destroy_user_session_path, method: :delete %></i>
        </li>
         <% else %>
        <li>
            <li><i class="fas fa-home">
         <%= link_to "Home", root_path %></i>
         <i class="fas fa-link">
         <%= link_to "About", home_about_path %></i>
         <i class="fas fa-user-plus"></i>
         <%= link_to "sign up", new_user_registration_path %></i>
         <i class="fas fa-sign-in-alt">
         <%= link_to "login", new_user_session_path %></i>
        </li>
         <% end %>
        </ul>
       </div>

    </div>
  </nav>

  　<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

   </div>

</header>

<main class="mb-auto">
    <%= yield %>
</main>

     <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  </body>
</html>