bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   get 'home/about' => 'homes#about'
   get 'user/:id/top' => 'users#top', as: 'top'
   get 'user/:id/about' => 'users#about', as: 'about'

   get '/search', to: 'searchs#search'

   get 'search/result' => 'searchs#result'

  resources :users, only: [:create, :index, :show, :destroy, :edit, :update, :delete]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update, :delete] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create]
   end

  resources :book_comments, only: [:destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
      else
      @books = Book.all
      render 'index'
      end
  end

  def index
    @newbook = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user

  end

  def show
    @newbook = Book.new
    @users = User.all
    @book = Book.find(params[:id])
    @user =  @book.user
    @book_comment = BookComment.new
    @oouser = User.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.all
    if @book.user.id != current_user.id
     redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

   def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
   end

   def delete
   flash[:notice] = "Signed out successfully."
   end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/views/books/edit.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <% if @book.errors.any? %>
   <%= @book.errors.count %>error
   <% @book.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
   <% end %>


<h2>Editing Book</h2>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
   <div class="form-group">
   <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
   </div>
<% end %>

<%= link_to "Show", book_path %> |
<%= link_to "Back", books_path %>

 </div>
 </div>
 </div>
</main>

bookers2/app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
  <div class="row">
  <div class="col-md-3">

   <% if @newbook.errors.any? %>
   <%= @newbook.errors.count %>error
   <% @newbook.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
   <% end %>

  <h1>User info</h1>
  <table class="table">
  <tbody>
  <% if @user = current_user %>
  <tr><th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th></tr>
  <tr><th>name：<%= @user.name %></th></tr>
  <tr><th>introduction：<%= @user.introduction %></th></tr>
  <% end %>
  <tr><th>follows<th><%= link_to "#{@user.follower.count}", top_path(@user) %></th></th></tr>
  <tr><th>followers<th><%= link_to "#{@user.followed.count}", about_path(@user) %></th></th></tr>
  </tbody>
  </table>

  <%= link_to edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

  <h3>New book</h3>
  <%= form_with model: @newbook, local:true do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: 'btn btn-success' %>
  <% end %>
  </div>

 <div class="col-md-8 offset-md-1">
 <table class="table table-hover table-inverse">
 <h4>Books</h4>
 <thead>
  <th> </th>
  <th>Title </th>
  <th>Opinion </th>
  <th colspan="3"></th>
  <tr></tr>

  <% @books.each do |book| %>
  <tr>
  <th><%= link_to attachment_image_tag(book.user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg"), user_path(book.user) %></th>
  <th><%= link_to book.title, book_path(book.id) %></th>
  <th><%= book.body %></th>

  <th>
     <div class="favorites-btn_<%= book.id %>" >
       <%= render 'favorites/favorites-btn', book: book %>
     </div>
  </th>

   <th><p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p></th>

   <% end %>
   </tr>
 <thead>
 </table>
 </div>

 </div>
 </div>
</main>

bookers2/app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
  <div class="row">
  <div class="col-md-3">

   <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

  <h1>User info</h1>
  <table class="table">
  <tbody>
  <tr><th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th></tr>
  <tr><th>name：<%= @user.name %></th></tr>
  <tr><th>introduction：<%= @user.introduction %></th></tr>
  <tr><th>follows<th><%= link_to "#{@oouser.follower.count}", top_path(@oouser) %></th></th></tr>
  <tr><th>followers<th><%= link_to "#{@oouser.followed.count}", about_path(@oouser) %></th></th></tr>
  </tbody>
  </table>

<%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

  <% unless @oouser == current_user %>
  <% if current_user.following?(@oouser) %>
    <%= link_to 'フォロー外す', unfollow_path(@oouser.id), class:  'btn btn-primary btn-block', method: :POST %>
  <% else %>
    <%= link_to 'フォローする', follow_path(@oouser.id), class: 'btn btn-success', method: :POST %>
  <% end %>
<% end %>
<p></p>

<h3>New book</h3>
 <%= form_with model: @newbook, local:true do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: 'btn btn-success' %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
 <h4>Book detail</h4>
 <table class="table table-hover table-inverse">

  <thead>
  <th> </th>
  <th> </th>
  <th> </th>
  <th> </th>
  <th> </th>
  <th> </th>
  <th> </th>
  <th colspan="7"></th>
  <tr></tr>
  <tr>
  <th><%= link_to user_path(@book.user) , target: "_blank" do %>
  　　　<%= attachment_image_tag(@book.user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg") %>
  　 　<%= @book.user.name  %>
　　　<% end %></th>
  <th><%= link_to @book.title, book_path(@book.id) %></th>
  <th><%= @book.body %></th>
      <% if @user.id == current_user.id %>
  <th><%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-success' %></th>
  <th><%= link_to "Destroy", book_path(@book.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に消しますか?" %></th>
      <% end %>

　<th>
　    <div class="favorites-btn_<%= @book.id %>" >
       <%= render 'favorites/favorites-btn', book: @book %>
      </div>
  </th>

   <th>コメント件数：<%= @book.book_comments.count %></th>
  </tr>
  <thead>
 </table>

    <div class="comments-btn">
    <%= render 'book_comments/comments-btn', book_comment: @book_comment, book: @book, user: @user %>
    </div>

 </div>

 </div>
 </div>
</main>