bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   get 'home/about' => 'homes#about'
   get 'user/:id/top' => 'users#top', as: 'top'
   get 'user/:id/about' => 'users#about', as: 'about'

   get '/search', to: 'searchs#search'

   get 'search/result' => 'searchs#result'

  resources :users, only: [:create, :index, :show, :destroy, :edit, :update, :delete]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update, :delete] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create]
   end

  resources :book_comments, only: [:destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    #favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    favorite.destroy
  end
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/views/favorites/_favorites-btn.html.erb
    <% if book.favorited_by?(current_user) %>
        <p><%= link_to "#{book.favorites.count}", book_favorites_path(book.id), method: :delete, remote: true, class:"fas fa-heart", :style => "color: red;" %><p>
    <% else %>
        <p><%= link_to "#{book.favorites.count}", book_favorites_path(book.id), method: :post, remote: true, class:"fas fa-heart", :style => "color: royalblue;" %></p>
    <% end %>

bookers2/app/views/favorites/create.js.erb
$(".favorites-btn_<%= @book.id %>").html("<%= j(render partial: 'favorites/favorites-btn', locals: {book: @book}) %>");

bookers2/app/views/favorites/destroy.js.erb
$(".favorites-btn_<%= @book.id %>").html("<%= j(render partial: 'favorites/favorites-btn', locals: {book: @book}) %>");