bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   get 'home/about' => 'homes#about'
   get 'user/:id/top' => 'users#top', as: 'top'
   get 'user/:id/about' => 'users#about', as: 'about'

   get '/search', to: 'searchs#search'

   get 'search/result' => 'searchs#result'

  resources :users, only: [:create, :index, :show, :destroy, :edit, :update, :delete]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update, :delete] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create]
   end

  resources :book_comments, only: [:destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id

    @user =  @book.user
    @book_comment = BookComment.new

    if comment.save
    flash[:notice] = "You have created comment successfully."
    else
      flash[:notice] = "空コメント不可"
      redirect_to book_path(@book)
    end
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book = Book.find(@book_comment.book.id)
    @user =  @book.user
    @book_comment.destroy
    @book_comment = BookComment.new

    flash[:notice] = "You have deleted comment successfully."
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/views/book_comments/_comments-btn.html.erb
  
    <div class="comments">
      <% book.book_comments.each do |book_comment| %>
       <br><%= attachment_image_tag(book.user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg") %>
        <%= book_comment.user.name %>
        <%= book_comment.comment %>

        <% if book_comment.user == current_user %>
         <% if user.id == current_user.id %>

           <%= link_to "Destroy", book_comment_path(book_comment), class: 'btn btn-danger', method: :delete, remote: true, "data-confirm" => "本当に消しますか?" %>

         <% end %>
        <% end %></br>
       <% end %>
    </div>

    <div class="new-comment">
     <%= form_with(model:[book, book_comment], remote: true) do |f| %>
      <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
      <%= f.submit "送信する" %>
     <% end %>
    </div>

bookers2/app/views/book_comments/create.js.erb
$(".comments-btn").html("<%= j(render partial: 'book_comments/comments-btn', locals: {book: @book, book_comment: @book_comment, user: @user}) %>");

bookers2/app/views/book_comments/destroy.js.erb
$(".comments-btn").html("<%= j(render partial: 'book_comments/comments-btn', locals: {book: @book, book_comment: @book_comment, user: @user}) %>");